#!/bin/sh -e
alias w="which >/dev/null"

w bundler || die "bundler is not installed. Try to install 'gem install bundler'"
bundle install

calabash-android resign dkitcordova.apk

adb devices || die "No devices found."


