#!/bin/sh
alias w="which >/dev/null"

w calabash-android || die "calabash-android is not installed. Try to install gem install calabash-android"

calabash-android resign dkitAndroid-1.3.apk

adb devices || die "No devices found."

/Applications/Genymotion.app/Contents/MacOS/player --vm-name "Google Nexus 7 2013 - 4.4.2 - API 19 - 1200x1920"



